<a href="https://colab.research.google.com/github/suryawahyus/MachineLearning/blob/main/UAS/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

**Apa itu PyTorch?**
PyTorch adalah sebuah pustaka komputasi ilmiah open-source yang banyak digunakan dalam pengembangan aplikasi pembelajaran mesin (machine learning) dan pembelajaran mendalam (deep learning). Awalnya dikembangkan oleh tim peneliti dan insinyur di Facebook's AI Research lab, PyTorch kini menjadi salah satu kerangka kerja (framework) terdepan dalam bidang kecerdasan buatan.

**Fungsi PyTorch:**
1. **Tensor Computing (seperti NumPy, tetapi dengan kemampuan GPU)**: PyTorch menyediakan struktur data inti yang disebut 'Tensor', mirip dengan array dalam NumPy, tetapi dengan dukungan komputasi pada GPU yang mempercepat proses komputasi.
2. **Pembelajaran Mendalam**: PyTorch menyediakan modul dan kelas untuk membangun dan melatih jaringan saraf tiruan. Ini termasuk fasilitas untuk autograd (perhitungan gradien otomatis), yang sangat berguna untuk backpropagation dalam pelatihan jaringan.
3. **Pengembangan Prototipe yang Fleksibel dan Interaktif**: PyTorch mendukung pendekatan yang lebih imperatif dan dinamis untuk pengembangan model, yang sering kali lebih intuitif dan mudah diadaptasi untuk penelitian dan pengembangan prototipe.
4. **Integrasi dengan Ekosistem Python**: PyTorch terintegrasi dengan baik dengan ekosistem Python yang lebih luas, termasuk pustaka seperti NumPy, SciPy, dan Pandas.

**Keunggulan PyTorch:**
1. **Interface yang User-Friendly**: PyTorch dikenal karena memiliki API yang jelas dan mudah dipahami, memudahkan para pengembang dan peneliti untuk membuat dan bereksperimen dengan model-model AI.
2. **Grafik Komputasi Dinamis (Dynamic Computational Graphs)**: Dikenal sebagai *define-by-run* approach, di mana grafik komputasi dibangun saat kode dijalankan. Hal ini memungkinkan perubahan lebih fleksibel pada grafik selama runtime, yang sangat berguna untuk penelitian.
3. **Komunitas yang Kuat dan Berkembang**: Sebagai salah satu framework populer, PyTorch didukung oleh komunitas yang besar dan aktif, menyediakan banyak sumber daya pembelajaran, dokumentasi, dan forum diskusi.
4. **Dukungan Luas untuk Penelitian dan Pengembangan**: PyTorch banyak digunakan dalam penelitian AI karena kemudahannya dalam mengimplementasikan ide-ide baru dan eksperimen, serta memiliki dukungan untuk alat-alat penelitian canggih.
5. **Integrasi dengan Ekosistem Machine Learning**: Mendukung integrasi dengan ekosistem machine learning yang lebih besar, termasuk pustaka untuk visualisasi data, pemrosesan data, dan lain-lain.

PyTorch menjadi pilihan utama bagi banyak peneliti dan insinyur di bidang AI karena kombinasi keunggulan ini, terutama dalam hal fleksibilitas dan kemudahan penggunaan.
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(5, 5)`.


In [10]:
# Mengimpor torch
import torch

# Membuat tensor acak
tensor_acak = torch.rand((5, 5))
print(tensor_acak)


tensor([[0.6604, 0.1303, 0.3498, 0.3824, 0.8043],
        [0.3186, 0.2908, 0.4196, 0.3728, 0.3769],
        [0.0108, 0.9455, 0.7661, 0.2634, 0.1880],
        [0.5174, 0.7849, 0.1412, 0.3112, 0.7091],
        [0.1775, 0.4443, 0.1230, 0.9638, 0.7695]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 5)` (hint: you may have to transpose the second tensor).

In [13]:
# Membuat tensor acak lain
tensor_acak_lain = torch.rand((1, 5))

# Melakukan perkalian matriks
hasil_perkalian = tensor_acak @ tensor_acak_lain.T
print(hasil_perkalian, hasil_perkalian.size())

tensor([[1.5878],
        [1.1858],
        [1.4385],
        [1.7565],
        [1.7080]]) torch.Size([5, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
tensor([[1.0015],
        [0.7964],
        [0.9888],
        [0.9036],
        [1.1845]])
```

In [15]:
# Mengatur seed manual
torch.manual_seed(0)

# Membuat dua tensor acak
tensor_acak_1 = torch.rand((5, 5))
tensor_acak_2 = torch.rand((1, 5))

# Mengalikan matriks tensor
hasil_perkalian = tensor_acak_1 @ tensor_acak_2.T
print(hasil_perkalian, hasil_perkalian.size())


tensor([[1.1488],
        [1.1704],
        [0.7175],
        [1.1156],
        [1.5817]]) torch.Size([5, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Mengatur seed acak di GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Mengatur seed acak
torch.manual_seed(1234)

# Memeriksa akses ke GPU
if torch.cuda.is_available():
    # Membuat dua tensor acak di GPU
    tensor_a = torch.rand((2, 3), device='cuda')
    tensor_b = torch.rand((2, 3), device='cuda')
    print("Perangkat:", tensor_a.device)
    print(tensor_a)
    print(tensor_b)


Perangkat: cuda:0
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Melakukan perkalian matriks pada tensor_A dan tensor_B
hasil_perkalian = tensor_a @ tensor_b.T
print(hasil_perkalian)


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Menemukan nilai maksimum
nilai_max = hasil_perkalian.max()
print("Nilai Maksimum:", nilai_max)

# Menemukan nilai minimum
nilai_min = hasil_perkalian.min()
print("Nilai Minimum:", nilai_min)


Nilai Maksimum: tensor(0.7668, device='cuda:0')
Nilai Minimum: tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
# Menemukan arg max
indeks_max = hasil_perkalian.argmax()
print("Indeks Maksimum:", indeks_max)

# Menemukan arg min
indeks_min = hasil_perkalian.argmin()
print("Indeks Minimum:", indeks_min)


Indeks Maksimum: tensor(1, device='cuda:0')
Indeks Minimum: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Mengatur seed
torch.manual_seed(7)

# Membuat tensor acak
tensor_acak = torch.rand((1, 1, 1, 10))
print(tensor_acak, tensor_acak.size())

# Menghilangkan dimensi tunggal
tensor_baru = tensor_acak.squeeze()
print(tensor_baru, tensor_baru.size())


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
